# Generated by Django 3.1.7 on 2022-01-04 16:48

import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyProvider",
            fields=[
                (
                    "name",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("provider_url", models.CharField(max_length=256)),
                ("last_update_time", models.DateTimeField()),
            ],
            options={
                "verbose_name": "key provider",
                "verbose_name_plural": "key providers",
            },
        ),
        migrations.CreateModel(
            name="StoredPublicKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_identifier", models.CharField(max_length=512)),
                (
                    "key_type",
                    models.CharField(
                        choices=[("SECP256R1", "SECP256R1")], max_length=32
                    ),
                ),
                ("key", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider",
                        to="special.keyprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "stored public key",
                "verbose_name_plural": "stored public keys",
            },
        ),
    ]
