# Generated by Django 3.1.7 on 2023-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thunderstore_wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipage",
            options={"ordering": ("wiki", "slug")},
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["wiki", "slug"], name="thunderstor_wiki_id_9975db_idx"
            ),
        ),
    ]
