# Generated by Django 2.1.2 on 2019-05-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamichtml',
            options={'verbose_name': 'Dynamic HTML', 'verbose_name_plural': 'Dynamic HTML'},
        ),
    ]
