# Generated by Django 2.1.2 on 2019-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("frontend", "0003_add_placement_info")]

    operations = [
        migrations.AddField(
            model_name="dynamichtml",
            name="ordering",
            field=models.IntegerField(default=0),
        )
    ]
