# Generated by Django 2.1.2 on 2019-05-29 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0013_package_cache_latest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploaderidentitymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploader_identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
