# Generated by Django 2.2.6 on 2019-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0020_fetch_version_file_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageversion",
            name="file_size",
            field=models.PositiveIntegerField(),
        ),
    ]
