# Generated by Django 2.2.6 on 2019-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_incomingjwtauthconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingjwtauthconfiguration",
            name="secret_type",
            field=models.CharField(
                choices=[("HS256", "HS256"), ("RS256", "RS256")], max_length=16
            ),
        ),
    ]
