# Generated by Django 3.0.4 on 2020-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_webhook_exclude_categories'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, related_name='webhooks', to='community.PackageCategory'),
        ),
    ]
