# Generated by Django 3.0.4 on 2020-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_add_webhook_exclude_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="allow_nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
