# Generated by Django 3.0.4 on 2020-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_add_community_links'),
        ('webhooks', '0004_add_webhook_inclusion_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='community_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='community.CommunitySite'),
        ),
    ]
