# Generated by Django 3.1.7 on 2023-01-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0007_add_community_to_webhook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhook",
            name="community_site",
        ),
    ]
