# Generated by Django 3.1.7 on 2023-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0026_schedule_aggregated_fields_refresh"),
        ("webhooks", "0008_remove_community_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditWebhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("webhook_url", models.CharField(max_length=2083)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "match_communities",
                    models.ManyToManyField(
                        help_text="Only match events from these communities. If empty, match all communities.",
                        related_name="audit_webhooks",
                        to="community.Community",
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
