# Generated by Django 2.1.2 on 2019-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_add_packageversiondownloadevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependants", to="repository.PackageVersion"
            ),
        ),
    ]
