# Generated by Django 2.1.2 on 2019-04-06 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_add_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
