# Generated by Django 2.1.2 on 2019-05-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_package_remove_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
