# Generated by Django 2.2.6 on 2019-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0018_add_discord_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="file_size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
