# Generated by Django 3.1.4 on 2020-12-20 13:21

from django.db import migrations, models
from django.db.models import Value
from django.db.models.functions import Replace


def set_default(apps, schema_editor):
    for model_name in ("Package", "PackageVersion"):
        for model in apps.get_model("repository", model_name):
            model.objects.update(display_name=Replace("name", Value("_"), Value(" ")))


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0022_add_package_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="display_name",
            field=models.CharField(null=True, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packageversion",
            name="display_name",
            field=models.CharField(null=True, max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(set_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="package",
            name="display_name",
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packageversion",
            name="display_name",
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
    ]
