# Generated by Django 3.1.6 on 2021-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0023_add_cache_refresh_celery_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploaderidentity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
