# Generated by Django 3.1.4 on 2020-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0023_add_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="license",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
