# Generated by Django 3.1.5 on 2021-01-17 18:25

import django.db.models.deletion
import ulid2
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0023_add_cache_refresh_celery_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccountMetadata",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_service_account", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_accounts",
                        to="repository.uploaderidentity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_account_metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
