# Generated by Django 3.1.6 on 2021-02-20 22:11

from django.db import migrations, models

import thunderstore.repository.validators


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0024_add_uploader_identity_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploaderidentity",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    thunderstore.repository.validators.PackageReferenceComponentValidator(
                        "Author name"
                    )
                ],
            ),
        ),
    ]
