# Generated by Django 3.1.7 on 2021-10-28 12:47

from django.db import migrations, models

import thunderstore.repository.validators


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0027_rename_uploader_identity_to_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            thunderstore.repository.validators.PackageReferenceComponentValidator(
                                "Namespace name"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="namespaces",
            field=models.ManyToManyField(
                related_name="teams", to="repository.Namespace"
            ),
        ),
    ]
