# Generated by Django 3.1.7 on 2021-11-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0029_create_namespaces_for_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="namespace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="repository.namespace",
            ),
        ),
    ]
