# Generated by Django 3.1.7 on 2022-01-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0031_add_namespaces_to_existing_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="namespace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="repository.namespace",
            ),
        ),
    ]
