# Generated by Django 3.1.7 on 2022-04-02 02:35

import django.core.validators
import storages.backends.s3boto3
from django.db import migrations, models

import thunderstore.repository.models.package_version


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0033_add_s3_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="donation_link",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[django.core.validators.URLValidator(["https"])],
            ),
        )
    ]
