# Generated by Django 3.1.7 on 2023-09-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_add_group"),
        ("repository", "0038_add_wiki"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="file_tree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="package_versions",
                to="storage.datablobgroup",
            ),
        ),
    ]
