# Generated by Django 3.1.7 on 2023-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0039_add_package_file_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="show_decompilation_results",
            field=models.TextField(
                choices=[("NONE", "None"), ("YES", "Yes"), ("NO", "No")], default="NONE"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="show_decompilation_results",
            field=models.TextField(
                choices=[("NONE", "None"), ("YES", "Yes"), ("NO", "No")], default="NONE"
            ),
        ),
    ]
