# Generated by Django 3.1.7 on 2023-11-14 09:27

from django.db import migrations, models

import thunderstore.core.mixins
import thunderstore.utils.makemigrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0041_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIExperimentalPackageIndexCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=thunderstore.utils.makemigrations.StubStorage(),
                        upload_to=thunderstore.core.mixins.get_package_cache_filepath,
                    ),
                ),
                ("content_type", models.TextField()),
                ("content_encoding", models.TextField()),
                ("last_modified", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="apiexperimentalpackageindexcache",
            index=models.Index(
                fields=["last_modified"], name="repository__last_mo_1ce042_idx"
            ),
        ),
    ]
