# Generated by Django 3.1.7 on 2023-12-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0043_add_package_index_task_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": (
                    ("deprecate_package", "Can manage package deprecation status"),
                )
            },
        ),
    ]
