# Generated by Django 3.1.7 on 2024-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0049_add_package_installer"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageinstaller",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packageinstaller",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
