# Generated by Django 3.1.7 on 2024-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0051_bigint_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageversion",
            name="readme",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="packageversion",
            name="website_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
