# Generated by Django 3.1.7 on 2024-05-22 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_add_group"),
        ("repository", "0053_schedule_chunked_package_caching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiv1chunkedpackagecache",
            name="index",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chunked_package_indexes",
                to="storage.datablob",
            ),
        ),
    ]
