# Generated by Django 3.1.7 on 2024-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0054_alter_chunked_package_cache_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("skipped", "skipped"),
                    ("immune", "immune"),
                ],
                default="skipped",
                max_length=512,
            ),
        ),
    ]
