# Generated by Django 3.1.7 on 2024-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0056_create_default_visibility_for_existing_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageversion",
            name="review_status",
            field=models.TextField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("skipped", "skipped"),
                    ("immune", "immune"),
                ],
                default="skipped",
            ),
        ),
    ]
