# Generated by Django 3.1.7 on 2025-05-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        ("repository", "0057_packageversion_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="visibility",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.visibilityflags",
            ),
        ),
    ]
