# Generated by Django 3.1.7 on 2025-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0057_team_max_file_count_per_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="review_status",
            field=models.TextField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("skipped", "skipped"),
                    ("immune", "immune"),
                ],
                default="skipped",
            ),
        ),
    ]
