# Generated by Django 3.1.7 on 2025-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0060_create_default_visibility_for_existing_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageversion",
            name="review_status",
            field=models.TextField(
                choices=[
                    ("unreviewed", "unreviewed"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="unreviewed",
            ),
        ),
    ]
