# Generated by Django 3.1.7 on 2025-08-27 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0061_alter_packageversion_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("added", "Added"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                            ("disbanded", "Disbanded"),
                            ("updated donation link for", "Updated Donation Link"),
                            ("created service account for", "Created Service Account"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlogs_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teamlogs_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="repository.team",
                    ),
                ),
            ],
            options={
                "ordering": ("datetime_created",),
            },
        ),
    ]
