# Generated by Django 3.1.7 on 2025-12-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0062_delete_namespaces_without_team_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="namespaces",
                to="repository.team",
            ),
        ),
    ]
