# Generated by Django 4.2.30 on 2026-09-15 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0065_delete_packageversiondownloadevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="changelog_override",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="readme_override",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="readme_override_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="readme_override_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readme_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="changelog_override_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageversion",
            name="changelog_override_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changelog_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PackageVersionMarkdownRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        choices=[("readme", "README"), ("changelog", "CHANGELOG")],
                        max_length=9,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("is_override", models.BooleanField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="markdown_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markdown_revisions",
                        to="repository.packageversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["version", "document", "-id"],
                        name="markdown_revision_history_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="packageversionmarkdownrevision",
            constraint=models.CheckConstraint(
                check=models.Q(("document__in", ["readme", "changelog"])),
                name="markdown_revision_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageversionmarkdownrevision",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("content__isnull", False),
                    models.Q(("document", "changelog"), ("is_override", False)),
                    _connector="OR",
                ),
                name="markdown_revision_content",
            ),
        ),
    ]
