# Generated by Django 3.1.7 on 2026-03-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0065_delete_packageversiondownloadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='changelog_override',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='readme_override',
            field=models.TextField(blank=True, null=True),
        ),
    ]
