# Generated by Django 3.1.7 on 2026-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0039_add_game_version"),
        ("repository", "0065_delete_packageversiondownloadevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageversion",
            name="game_versions",
            field=models.ManyToManyField(
                blank=True, related_name="package_versions", to="community.GameVersion"
            ),
        ),
    ]
