# Generated by Django 3.1.7 on 2026-09-14 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0067_add_markdown_override_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageVersionMarkdownRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        choices=[("readme", "README"), ("changelog", "CHANGELOG")],
                        max_length=9,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("is_override", models.BooleanField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="markdown_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markdown_revisions",
                        to="repository.packageversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "default_permissions": ("view",),
            },
        ),
        migrations.AddIndex(
            model_name="packageversionmarkdownrevision",
            index=models.Index(
                fields=["version", "document", "-id"],
                name="markdown_revision_history_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageversionmarkdownrevision",
            constraint=models.CheckConstraint(
                check=models.Q(document__in=["readme", "changelog"]),
                name="markdown_revision_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageversionmarkdownrevision",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("content__isnull", False),
                    models.Q(("document", "changelog"), ("is_override", False)),
                    _connector="OR",
                ),
                name="markdown_revision_content",
            ),
        ),
    ]
