# Generated by Django 3.1.7 on 2022-10-24 21:20

import ulid2
from django.db import migrations, models

import thunderstore.modpacks.models.legacyprofile
import thunderstore.utils.makemigrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyProfile",
            fields=[
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=thunderstore.utils.makemigrations.StubStorage(),
                        upload_to=thunderstore.modpacks.models.legacyprofile.get_legacy_profile_file_path,
                    ),
                ),
                ("file_size", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
