# Generated by Django 3.1.7 on 2023-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modpacks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyprofile",
            name="file_sha256",
            field=models.CharField(
                blank=True, editable=False, max_length=512, null=True
            ),
        ),
    ]
