# Generated by Django 3.1.7 on 2024-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modpacks", "0002_add_file_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyprofile",
            name="file_sha256",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=512, null=True
            ),
        ),
    ]
