# Generated by Django 3.1.7 on 2023-04-02 11:58

from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    dependencies = [
        ('modpacks', '0002_add_file_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyProfileMetaData',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, editable=False, primary_key=True, serialize=False)),
                ('profile_meta_data', models.JSONField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_datas', to='modpacks.legacyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
