# Generated by Django 2.1.2 on 2019-04-04 19:12

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='maintainers',
            field=models.ManyToManyField(blank=True, related_name='maintaned_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
