# Generated by Django 2.1.2 on 2019-04-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("repository", "0006_package_pinned")]

    operations = [
        migrations.RenameField(
            model_name="package", old_name="pinned", new_name="is_pinned"
        )
    ]
