# Generated by Django 2.1.2 on 2019-08-10 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0014_update_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_ratings', to='repository.Package')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='packagerating',
            unique_together={('rater', 'package')},
        ),
    ]
