# Generated by Django 3.1.7 on 2024-01-04 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usermedia", "0002_add_cleanup_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermedia",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usermedia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
