# Generated by Django 3.1.7 on 2024-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermedia", "0003_usermedia_owner_set_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermedia",
            name="size",
            field=models.PositiveBigIntegerField(),
        ),
    ]
