from rest_framework import serializers
from rest_framework.pagination import PageNumberPagination

from thunderstore.api.cyberstorm.serializers import CyberstormPackagePreviewSerializer


class PackageDependenciesPaginator(PageNumberPagination):
    page_size = 20


class PackageListPaginator(PageNumberPagination):
    page_size = 20

    def get_schema_fields(self, view):
        """
        By default this would return page (via page_query_param
        attribute) and page_size (via page_size_query_param attribute).
        The former would clash with the page field defined in our
        PackageListRequestSerializer, breaking the API documentation
        generated by drf_yasg. Returning an empty list means we have the
        control and responsibility to make sure the documentation
        matches reality.
        """
        return []


class PackageListResponseSerializer(serializers.Serializer):
    """
    Matches DRF's PageNumberPagination response.
    """

    count = serializers.IntegerField(min_value=0)
    previous = serializers.CharField(allow_null=True)
    next = serializers.CharField(allow_null=True)  # noqa: A003
    results = CyberstormPackagePreviewSerializer(many=True)
