# Generated by Django 3.1.7 on 2022-02-28 15:39

import django.contrib.postgres.fields.citext
import django.db.models.deletion
import ulid2
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyProvider",
            fields=[
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=64, unique=True
                    ),
                ),
                ("provider_url", models.CharField(max_length=256)),
                ("datetime_last_synced", models.DateTimeField()),
            ],
            options={
                "verbose_name": "key provider",
                "verbose_name_plural": "key providers",
            },
        ),
        migrations.CreateModel(
            name="StoredPublicKey",
            fields=[
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_identifier", models.TextField()),
                ("key_type", models.TextField(choices=[("SECP256R1", "SECP256R1")])),
                ("key", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_public_keys",
                        to="ts_github.keyprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "stored public key",
                "verbose_name_plural": "stored public keys",
            },
        ),
        migrations.AddConstraint(
            model_name="storedpublickey",
            constraint=models.UniqueConstraint(
                fields=("provider", "key_identifier"),
                name="one_key_identifier_per_provider",
            ),
        ),
    ]
