# Generated by Django 3.1.7 on 2024-10-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0004_add_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_service_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
