# Generated by Django 3.1.7 on 2026-01-03 23:23

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # Required for AddIndexConcurrently

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        # Giant table, AddIndexConcurrently avoids blocking the table for writes.
        AddIndexConcurrently(
            model_name='packageversiondownloadevent',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='metrics_pac_timesta_57fb43_brin'),
        ),
    ]
