# Generated by Django 3.1.7 on 2022-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_add_community_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamichtml",
            name="placement",
            field=models.CharField(
                choices=[
                    ("ads_txt", "ads_txt"),
                    ("robots_txt", "robots_txt"),
                    ("html_head", "html_head"),
                    ("html_body_beginning", "html_body_beginning"),
                    ("content_beginning", "content_beginning"),
                    ("content_end", "content_end"),
                    ("frontpage_beginning", "frontpage_beginning"),
                    ("frontpage_end", "frontpage_end"),
                ],
                db_index=True,
                max_length=256,
            ),
        ),
    ]
