# Generated by Django 3.1.7 on 2022-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_add_main_left_and_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamichtml",
            name="placement",
            field=models.CharField(
                choices=[
                    ("ads_txt", "ads_txt"),
                    ("robots_txt", "robots_txt"),
                    ("html_head", "html_head"),
                    ("html_body_beginning", "html_body_beginning"),
                    ("content_beginning", "content_beginning"),
                    ("content_footer", "content_footer"),
                    ("content_end", "content_end"),
                    ("main_content_left", "main_content_left"),
                    ("main_content_right", "main_content_right"),
                ],
                db_index=True,
                max_length=256,
            ),
        ),
    ]
