# Generated by Django 3.1.7 on 2023-03-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0022_add_block_auto_updates"),
        ("frontend", "0008_add_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityNavLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("href", models.TextField()),
                ("css_class", models.TextField(blank=True, null=True)),
                (
                    "target",
                    models.TextField(
                        choices=[
                            ("_blank", "Blank"),
                            ("_parent", "Parent"),
                            ("_self", "Self"),
                            ("_top", "Top"),
                        ],
                        default="_self",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("href", models.TextField()),
                ("css_class", models.TextField(blank=True, null=True)),
                (
                    "target",
                    models.TextField(
                        choices=[
                            ("_blank", "Blank"),
                            ("_parent", "Parent"),
                            ("_self", "Self"),
                            ("_top", "Top"),
                        ],
                        default="_self",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "title"),
            },
        ),
        migrations.AddIndex(
            model_name="navlink",
            index=models.Index(
                fields=["is_active", "order", "title"],
                name="frontend_na_is_acti_930286_idx",
            ),
        ),
        migrations.AddField(
            model_name="communitynavlink",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nav_links",
                to="community.community",
            ),
        ),
        migrations.AddIndex(
            model_name="communitynavlink",
            index=models.Index(
                fields=["community", "is_active", "order", "title"],
                name="frontend_co_communi_cf90b7_idx",
            ),
        ),
    ]
