# Generated by Django 3.1.7 on 2024-02-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_add_package_page_placeholder"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("href", models.TextField()),
                ("css_class", models.TextField(blank=True, null=True)),
                (
                    "target",
                    models.TextField(
                        choices=[
                            ("_blank", "Blank"),
                            ("_parent", "Parent"),
                            ("_self", "Self"),
                            ("_top", "Top"),
                        ],
                        default="_self",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("group_title", models.TextField()),
            ],
            options={
                "ordering": ("order", "title"),
            },
        ),
        migrations.AddIndex(
            model_name="footerlink",
            index=models.Index(
                fields=["is_active", "group_title", "order", "title"],
                name="frontend_fo_is_acti_3fbacf_idx",
            ),
        ),
    ]
