# Generated by Django 3.0.4 on 2020-09-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_add_package_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'verbose_name': 'package category', 'verbose_name_plural': 'package categories'},
        ),
    ]
