# Generated by Django 3.1.6 on 2021-02-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_add_is_listed_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitysite",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
