# Generated by Django 3.1.6 on 2021-03-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0011_add_community_site_is_listed_flag"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="packagelisting",
            constraint=models.UniqueConstraint(
                fields=("package", "community"), name="one_listing_per_community"
            ),
        ),
    ]
