# Generated by Django 3.1.6 on 2021-03-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0026_add_unique_constraints"),
        ("community", "0012_add_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagelisting",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_listings",
                to="repository.package",
            ),
        ),
    ]
