# Generated by Django 3.1.6 on 2021-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0013_rename_community_listings_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagecategory",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="packagecategory",
            constraint=models.UniqueConstraint(
                fields=("slug", "community"), name="unique_category_slug_per_community"
            ),
        ),
    ]
