# Generated by Django 3.1.6 on 2021-03-16 21:04

from django.db import migrations, models

import thunderstore.community.models.community_site


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0014_fix_category_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitysite",
            name="background_image",
            field=models.ImageField(
                blank=True,
                height_field="background_image_height",
                null=True,
                upload_to=thunderstore.community.models.community_site.get_community_filepath,
                width_field="background_image_width",
            ),
        ),
        migrations.AddField(
            model_name="communitysite",
            name="background_image_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="communitysite",
            name="background_image_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
