# Generated by Django 3.1.6 on 2021-03-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0027_comment_thread"),
        ("community", "0015_add_community_site_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagelisting",
            name="comments_thread",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_community_packagelisting",
                to="repository.thread",
            ),
        ),
    ]
