# Generated by Django 3.1.7 on 2021-05-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0017_add_package_approval_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagelisting",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagelisting",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
