# Generated by Django 3.1.7 on 2022-04-01 15:13

from django.db import migrations, models

import thunderstore.community.models.community


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0018_add_package_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                height_field="thumbnail_height",
                null=True,
                upload_to=thunderstore.community.models.community.get_community_filepath,
                width_field="thumbnail_width",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="thumbnail_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="thumbnail_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
