# Generated by Django 3.1.7 on 2022-05-08 18:53

from django.db import migrations, models

import thunderstore.community.models.community


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0018_add_package_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="background_image",
            field=models.ImageField(
                blank=True,
                height_field="background_image_height",
                null=True,
                upload_to=thunderstore.community.models.community.get_community_filepath,
                width_field="background_image_width",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="background_image_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="background_image_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="icon",
            field=models.ImageField(
                blank=True,
                height_field="icon_height",
                null=True,
                upload_to=thunderstore.community.models.community.get_community_filepath,
                width_field="icon_width",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="icon_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="icon_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="slogan",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
