# Generated by Django 3.1.7 on 2022-07-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0020_copy_community_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitysite",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="background_image_height",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="background_image_width",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="description",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="icon_height",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="icon_width",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="slogan",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="social_auth_discord_key",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="social_auth_discord_secret",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="social_auth_github_key",
        ),
        migrations.RemoveField(
            model_name="communitysite",
            name="social_auth_github_secret",
        ),
    ]
