# Generated by Django 3.1.7 on 2024-04-16 17:48

from django.db import migrations, models

import thunderstore.community.models.community


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0027_add_review_requested_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                height_field="cover_image_height",
                null=True,
                upload_to=thunderstore.community.models.community.get_community_filepath,
                width_field="cover_image_width",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="cover_image_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="cover_image_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
