# Generated by Django 3.1.7 on 2024-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0028_add_cover_image_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagelisting",
            name="is_auto_imported",
            field=models.BooleanField(default=False),
        ),
    ]
