# Generated by Django 3.1.7 on 2024-10-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        ("community", "0029_packagelisting_is_auto_imported"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagelisting",
            name="visibility",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.visibilityflags",
            ),
        ),
    ]
