# Generated by Django 3.1.7 on 2024-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0030_add_community_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="short_description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
