# Generated by Django 3.1.7 on 2025-02-20 10:29

from django.db import migrations, models

import thunderstore.community.models.community


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0031_community_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="community_icon",
            field=models.ImageField(
                blank=True,
                height_field="community_icon_height",
                null=True,
                upload_to=thunderstore.community.models.community.get_community_filepath,
                width_field="community_icon_width",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="community_icon_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="community",
            name="community_icon_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
