# Generated by Django 3.1.7 on 2025-01-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0031_community_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="has_mod_manager_support",
            field=models.BooleanField(default=True),
        ),
    ]
