# Generated by Django 3.1.7 on 2024-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0031_create_default_visibility_for_existing_listings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagelisting",
            name="review_status",
            field=models.TextField(
                choices=[
                    ("unreviewed", "unreviewed"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="unreviewed",
            ),
        ),
    ]
