# Generated by Django 3.1.7 on 2024-12-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0031_community_short_description"),
        ("community", "0032_auto_20241112_1930"),
    ]

    operations = []
