# Generated by Django 3.1.7 on 2025-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0034_add_search_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("moderator", "moderator"),
                    ("janitor", "janitor"),
                    ("member", "member"),
                ],
                default="member",
                max_length=64,
            ),
        ),
    ]
