# Generated by Django 3.1.7 on 2025-03-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        ("community", "0035_add_janitor_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagelisting",
            name="visibility",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.visibilityflags",
            ),
        ),
    ]
