# Generated by Django 3.1.7 on 2026-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0037_create_default_visibility_for_existing_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="background_image_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="community_icon_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="cover_image_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="hero_image_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="icon_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
