# Generated by Django 3.1.7 on 2026-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0037_create_default_visibility_for_existing_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="background_image_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="community_icon_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="cover_image_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="hero_image_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="icon_link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
