# Generated by Django 3.1.7 on 2026-07-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0038_auto_20260430_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "notifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ordered list of {"type": "critical"|"warning"|"info", "content": "text"} objects. Content is plain text; links use the [label](target) syntax with http(s) or root-relative (/...) targets only.',
                    ),
                ),
                (
                    "community",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="community.community",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
