# Generated by Django 3.1.7 on 2026-05-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0038_auto_20260430_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=256)),
                (
                    "release_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "release group",
                "verbose_name_plural": "release groups",
            },
        ),
        migrations.CreateModel(
            name="GameVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=64)),
                (
                    "release_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                    ),
                ),
                (
                    "release_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.releasegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "game version",
                "verbose_name_plural": "game versions",
            },
        ),
        migrations.AddConstraint(
            model_name="releasegroup",
            constraint=models.UniqueConstraint(
                fields=("slug", "community"), name="unique_release_group_per_community"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameversion",
            constraint=models.UniqueConstraint(
                fields=("version", "community"),
                name="unique_game_version_per_community",
            ),
        ),
    ]
