# Generated by Django 3.1.7 on 2026-06-22 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0065_delete_packageversiondownloadevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0038_auto_20260430_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeratorNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_moderator_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_notes",
                        to="community.community",
                    ),
                ),
                (
                    "package_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_notes",
                        to="community.packagelisting",
                    ),
                ),
                (
                    "package_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_notes",
                        to="repository.packageversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-datetime_created",),
            },
        ),
        migrations.AddConstraint(
            model_name="moderatornote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("community__isnull", False),
                        ("package_listing__isnull", True),
                        ("package_version__isnull", True),
                    ),
                    models.Q(
                        ("community__isnull", True),
                        ("package_listing__isnull", False),
                        ("package_version__isnull", True),
                    ),
                    models.Q(
                        ("community__isnull", True),
                        ("package_listing__isnull", False),
                        ("package_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="moderator_note_valid_target",
            ),
        ),
    ]
