name: Thunderstore App - Tag

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  trigger-release-workflow:
    uses: ./.github/workflows/_dispatch-infra-v2.yml
    with:
      workflow_file: build-thunderstore-app-tag.yml
      tag_name: ${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write
