name: Thunderstore App - Pre-release

on:
  release:
    types: [prereleased]

permissions:
  contents: read
  id-token: write

jobs:
  trigger-release-workflow:
    uses: ./.github/workflows/_dispatch-infra-v2.yml
    with:
      workflow_file: build-thunderstore-app-pre-release.yml
      tag_name: ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      id-token: write
